prog: cal_main.o add.o sub.o mul.o dur.o
	gcc -o prog cal_main.o add.o sub.o mul.o dur.o

cal_main.o : cal_main.c arithmetic.h
	gcc -I. -c cal_main.c

add.o : add.c arithmetic.h
	gcc -I. -c add.c

sub.o : sub.c arithmetic.h
	gcc -I. -c sub.c

mul.o : mul.c arithmetic.h
	gcc -I. -c mul.c

dur.o : dur.c arithmetic.h
	gcc -I. -c dur.c

clean:
	rm -rf prog cal_main.o add.o sub.o mul.o dur.o
